/**
 * ChronoSheets API
 * <div style=\'font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;\'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target=\'_BLANK\' href=\'http://tsheets.xyz/signup\'>http://tsheets.xyz/signup</a>.  </p></div><div id=\'cs-extra-info\'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Client { 
    /**
     * The ID of the client
     */
    Id?: number;
    /**
     * The ID of your organisation
     */
    OrganisationId?: number;
    /**
     * The name of the client
     */
    ClientName?: string;
    /**
     * The address line 1 of the client
     */
    ClientAddressLine1?: string;
    /**
     * The address line 2 of the client
     */
    ClientAddressLine2?: string;
    /**
     * The address suburb of the client
     */
    ClientSuburb?: string;
    /**
     * The address state of the client
     */
    ClientState?: string;
    /**
     * The postcode of the client
     */
    ClientPostCode?: string;
    /**
     * The contact person working under the client
     */
    PersonOfContact?: string;
    /**
     * The phone number of the client
     */
    ClientPhoneNumber?: string;
    /**
     * The mobile phone number of the client
     */
    ClientMobileNumber?: string;
    /**
     * The email address of the client
     */
    ClientEmailAddress?: string;
    /**
     * The website URL of the client
     */
    ClientWebURL?: string;
    /**
     * The number of projects under the client
     */
    ProjectCount?: number;
}

