/**
 * ChronoSheets API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CsApiInsertUserRequest {
    emailAddress?: string;
    firstName?: string;
    lastName?: string;
    isSubscribedToNewsletter?: boolean;
    roles?: number;
    alertSettings?: number;
    userName?: string;
    hourlyPayRate?: number;
    hourlyOvertimePayRate?: number;
    currentDate?: Date;
}
