/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CsApiRawReportItem {
    organisationId?: number;
    userId?: number;
    username?: string;
    emailAddress?: string;
    jobCode?: string;
    taskName?: string;
    clientName?: string;
    projectName?: string;
    startDate?: Date;
    endDate?: Date;
    spanSeconds?: number;
    description?: string;
    payAmount?: number;
    payOvertimeAmount?: number;
    tripCost?: number;
    tripDistanceMeters?: number;
}
