/**
 * ChronoSheets API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CsApiUpdateOrganisationRequest {
    organsationId?: number;
    organisationName?: string;
    addressLine01?: string;
    addressLine02?: string;
    organisationSuburb?: string;
    organisationState?: string;
    organisationPostcode?: string;
    organisationCountry?: string;
    organisationPhone?: string;
    organisationEmailAddress?: string;
}
