/**
 * ChronoSheets API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CsApiTimesheet {
    timesheetId?: number;
    userId?: number;
    jobId?: number;
    taskId?: number;
    startDateTime?: Date;
    endDateTime?: Date;
    description?: string;
    tripId?: number;
    fileAttachmentCount?: number;
    payAmount?: number;
    overtimePayAmount?: number;
    includesOvertime?: boolean;
}
