/**
 * ChronoSheets API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CsApiTimeSlot } from './csApiCsApiTimeSlot';


export interface CsApiUsualHoursDay {
    dayType?: CsApiUsualHoursDay.CsApiDayTypeEnum;
    timeSlots?: Array<CsApiTimeSlot>;
    deleteUsualHours?: Array<number>;
}
export namespace CsApiUsualHoursDay {
    export type CsApiDayTypeEnum = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
    export const CsApiDayTypeEnum = {
        Monday: 'Monday' as CsApiDayTypeEnum,
        Tuesday: 'Tuesday' as CsApiDayTypeEnum,
        Wednesday: 'Wednesday' as CsApiDayTypeEnum,
        Thursday: 'Thursday' as CsApiDayTypeEnum,
        Friday: 'Friday' as CsApiDayTypeEnum,
        Saturday: 'Saturday' as CsApiDayTypeEnum,
        Sunday: 'Sunday' as CsApiDayTypeEnum
    }
}
