/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CSTimesheetTask } from './cSCSTimesheetTask';


export interface CSApiResponseTimesheetTask {
    data?: CSTimesheetTask;
    status?: CSApiResponseTimesheetTask.CSStatusEnum;
    message?: string;
}
export namespace CSApiResponseTimesheetTask {
    export type CSStatusEnum = 'Succeeded' | 'FatalException' | 'GeneralError' | 'ValidationError' | 'UnAuthorized' | 'SessionExpired';
    export const CSStatusEnum = {
        Succeeded: 'Succeeded' as CSStatusEnum,
        FatalException: 'FatalException' as CSStatusEnum,
        GeneralError: 'GeneralError' as CSStatusEnum,
        ValidationError: 'ValidationError' as CSStatusEnum,
        UnAuthorized: 'UnAuthorized' as CSStatusEnum,
        SessionExpired: 'SessionExpired' as CSStatusEnum
    }
}
