/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CsApiClientSeriesReportItem } from './csApiCsApiClientSeriesReportItem';
import { CsApiClientTotalsReportItem } from './csApiCsApiClientTotalsReportItem';
import { CsApiJobSeriesReportItem } from './csApiCsApiJobSeriesReportItem';
import { CsApiJobTotalsReportItem } from './csApiCsApiJobTotalsReportItem';
import { CsApiProjectSeriesReportItem } from './csApiCsApiProjectSeriesReportItem';
import { CsApiProjectTotalsReportItem } from './csApiCsApiProjectTotalsReportItem';
import { CsApiTaskSeriesReportItem } from './csApiCsApiTaskSeriesReportItem';
import { CsApiTaskTotalsReportItem } from './csApiCsApiTaskTotalsReportItem';


export interface CsApiCombinedReportsData {
    seriesJobCodes?: Array<CsApiJobSeriesReportItem>;
    seriesTasks?: Array<CsApiTaskSeriesReportItem>;
    seriesClients?: Array<CsApiClientSeriesReportItem>;
    seriesProjects?: Array<CsApiProjectSeriesReportItem>;
    totalsJobCodes?: Array<CsApiJobTotalsReportItem>;
    totalsTasks?: Array<CsApiTaskTotalsReportItem>;
    totalsClients?: Array<CsApiClientTotalsReportItem>;
    totalsProjects?: Array<CsApiProjectTotalsReportItem>;
}
