/**
 * ChronoSheets API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CsApiCreateTripRequest {
    timesheetId?: number;
    vehicleId?: number;
    pathCoordsStringCsv?: string;
    distanceMeters?: number;
    mobilePlatform?: CsApiCreateTripRequest.CsApiMobilePlatformEnum;
}
export namespace CsApiCreateTripRequest {
    export type CsApiMobilePlatformEnum = 'Unknown' | 'iOS' | 'Android';
    export const CsApiMobilePlatformEnum = {
        Unknown: 'Unknown' as CsApiMobilePlatformEnum,
        IOS: 'iOS' as CsApiMobilePlatformEnum,
        Android: 'Android' as CsApiMobilePlatformEnum
    }
}
