/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CSBasicCoordinate } from './cSCSBasicCoordinate';


export interface CSGeofence { 
    geoFencingId?: number;
    orgId?: number;
    createdByUserId?: number;
    lastUpdatedByUserId?: number;
    name?: string;
    locationName?: string;
    coordinates?: Array<CSBasicCoordinate>;
    createdAt?: Date;
    updatedAt?: Date;
    triggerJobCodeId?: number;
    triggerTaskId?: number;
    triggerSettings?: CSGeofence.CSTriggerSettingsEnum;
    alertToOrgGroupId?: number;
    alertSettings?: CSGeofence.CSAlertSettingsEnum;
    startTimeHour?: number;
    startTimeMinute?: number;
    endTimeHour?: number;
    endTimeMinute?: number;
}
export namespace CSGeofence {
    export type CSTriggerSettingsEnum = 'None' | 'StartTimesheetWhenEntering' | 'StopTimesheetWhenEntering' | 'StartOnEnterStopOnLeave';
    export const CSTriggerSettingsEnum = {
        None: 'None' as CSTriggerSettingsEnum,
        StartTimesheetWhenEntering: 'StartTimesheetWhenEntering' as CSTriggerSettingsEnum,
        StopTimesheetWhenEntering: 'StopTimesheetWhenEntering' as CSTriggerSettingsEnum,
        StartOnEnterStopOnLeave: 'StartOnEnterStopOnLeave' as CSTriggerSettingsEnum
    };
    export type CSAlertSettingsEnum = 'None' | 'SendWhenEntering' | 'SendWhenExiting' | 'SendWhenEnteringOrExiting';
    export const CSAlertSettingsEnum = {
        None: 'None' as CSAlertSettingsEnum,
        SendWhenEntering: 'SendWhenEntering' as CSAlertSettingsEnum,
        SendWhenExiting: 'SendWhenExiting' as CSAlertSettingsEnum,
        SendWhenEnteringOrExiting: 'SendWhenEnteringOrExiting' as CSAlertSettingsEnum
    };
}
