/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CSOrganisationPricingPlan } from './cSCSOrganisationPricingPlan';


export interface CSOrganisation {
    id?: number;
    name?: string;
    addressLine01?: string;
    addressLine02?: string;
    suburb?: string;
    state?: string;
    postcode?: string;
    country?: string;
    phone?: string;
    emailAddress?: string;
    timezone?: string;
    subscriptionCustomerId?: string;
    signupToken?: string;
    isActive?: boolean;
    stripeCouponCode?: string;
    subscriptionSource?: CSOrganisation.CSSubscriptionSourceEnum;
    signUpSource?: CSOrganisation.CSSignUpSourceEnum;
    mobileSignUpCode?: string;
    subscriptionCycleStart?: Date;
    subscriptionCycleEnd?: Date;
    pricingPlans?: Array<CSOrganisationPricingPlan>;
}
export namespace CSOrganisation {
    export type CSSubscriptionSourceEnum = 'None' | 'Stripe' | 'AppleInApp' | 'GoogleInApp';
    export const CSSubscriptionSourceEnum = {
        None: 'None' as CSSubscriptionSourceEnum,
        Stripe: 'Stripe' as CSSubscriptionSourceEnum,
        AppleInApp: 'AppleInApp' as CSSubscriptionSourceEnum,
        GoogleInApp: 'GoogleInApp' as CSSubscriptionSourceEnum
    }
    export type CSSignUpSourceEnum = 'Desktop' | 'MobileiOS' | 'MobileAndroid';
    export const CSSignUpSourceEnum = {
        Desktop: 'Desktop' as CSSignUpSourceEnum,
        MobileiOS: 'MobileiOS' as CSSignUpSourceEnum,
        MobileAndroid: 'MobileAndroid' as CSSignUpSourceEnum
    }
}
