/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CSSaveClientRequest {
    id?: number;
    clientName?: string;
    clientAddressLine1?: string;
    clientAddressLine2?: string;
    clientSuburb?: string;
    clientState?: string;
    clientPostCode?: string;
    personOfContact?: string;
    clientPhoneNumber?: string;
    clientMobileNumber?: string;
    clientEmailAddress?: string;
    clientWebURL?: string;
}
