/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CSTimeSlot {
    dayType?: CSTimeSlot.CSDayTypeEnum;
    usualHourId?: number;
    startHour?: number;
    startMinute?: number;
    endHour?: number;
    endMinute?: number;
    isValid?: boolean;
}
export namespace CSTimeSlot {
    export type CSDayTypeEnum = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
    export const CSDayTypeEnum = {
        Monday: 'Monday' as CSDayTypeEnum,
        Tuesday: 'Tuesday' as CSDayTypeEnum,
        Wednesday: 'Wednesday' as CSDayTypeEnum,
        Thursday: 'Thursday' as CSDayTypeEnum,
        Friday: 'Friday' as CSDayTypeEnum,
        Saturday: 'Saturday' as CSDayTypeEnum,
        Sunday: 'Sunday' as CSDayTypeEnum
    }
}
