/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CSTranscription {
    id?: number;
    orgId?: number;
    fileAttachmentId?: number;
    created?: Date;
    status?: CSTranscription.CSStatusEnum;
    mediaType?: CSTranscription.CSMediaTypeEnum;
    contents?: string;
}
export namespace CSTranscription {
    export type CSStatusEnum = 'Saved' | 'Processing' | 'Completed' | 'FailedWithError';
    export const CSStatusEnum = {
        Saved: 'Saved' as CSStatusEnum,
        Processing: 'Processing' as CSStatusEnum,
        Completed: 'Completed' as CSStatusEnum,
        FailedWithError: 'FailedWithError' as CSStatusEnum
    }
    export type CSMediaTypeEnum = 'Other' | 'Mp3' | 'Mp4' | 'Wav' | 'Flac';
    export const CSMediaTypeEnum = {
        Other: 'Other' as CSMediaTypeEnum,
        Mp3: 'Mp3' as CSMediaTypeEnum,
        Mp4: 'Mp4' as CSMediaTypeEnum,
        Wav: 'Wav' as CSMediaTypeEnum,
        Flac: 'Flac' as CSMediaTypeEnum
    }
}
