/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CSTimeSlot } from './cSCSTimeSlot';


export interface CSUsualHoursDay {
    /**
     * Specify which day this collection of Roster timeslots is for (Monday-Sunday)
     */
    dayType?: CSUsualHoursDay.CSDayTypeEnum;
    /**
     * A collection of TimeSlots within this day
     */
    timeSlots?: Array<CSTimeSlot>;
    /**
     * Mark here which existing UsualHours are to be deleted
     */
    deleteUsualHours?: Array<number>;
}
export namespace CSUsualHoursDay {
    export type CSDayTypeEnum = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
    export const CSDayTypeEnum = {
        Monday: 'Monday' as CSDayTypeEnum,
        Tuesday: 'Tuesday' as CSDayTypeEnum,
        Wednesday: 'Wednesday' as CSDayTypeEnum,
        Thursday: 'Thursday' as CSDayTypeEnum,
        Friday: 'Friday' as CSDayTypeEnum,
        Saturday: 'Saturday' as CSDayTypeEnum,
        Sunday: 'Sunday' as CSDayTypeEnum
    }
}
