/**
 * ChronoSheets API
 * <div style=\'font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;\'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target=\'_BLANK\' href=\'http://tsheets.xyz/signup\'>http://tsheets.xyz/signup</a>.  </p></div><div id=\'cs-extra-info\'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BasicCoordinate } from './basicCoordinate';


export interface Geofence { 
    GeoFencingId?: number;
    OrgId?: number;
    CreatedByUserId?: number;
    LastUpdatedByUserId?: number;
    Name?: string;
    LocationName?: string;
    Coordinates?: Array<BasicCoordinate>;
    CreatedAt?: string;
    UpdatedAt?: string;
    TriggerJobCodeId?: number;
    TriggerTaskId?: number;
    TriggerSettings?: Geofence.TriggerSettingsEnum;
    AlertToOrgGroupId?: number;
    AlertSettings?: Geofence.AlertSettingsEnum;
    StartTimeHour?: number;
    StartTimeMinute?: number;
    EndTimeHour?: number;
    EndTimeMinute?: number;
}
export namespace Geofence {
    export type TriggerSettingsEnum = 'None' | 'StartTimesheetWhenEntering' | 'StopTimesheetWhenEntering' | 'StartOnEnterStopOnLeave';
    export const TriggerSettingsEnum = {
        None: 'None' as TriggerSettingsEnum,
        StartTimesheetWhenEntering: 'StartTimesheetWhenEntering' as TriggerSettingsEnum,
        StopTimesheetWhenEntering: 'StopTimesheetWhenEntering' as TriggerSettingsEnum,
        StartOnEnterStopOnLeave: 'StartOnEnterStopOnLeave' as TriggerSettingsEnum
    };
    export type AlertSettingsEnum = 'None' | 'SendWhenEntering' | 'SendWhenExiting' | 'SendWhenEnteringOrExiting';
    export const AlertSettingsEnum = {
        None: 'None' as AlertSettingsEnum,
        SendWhenEntering: 'SendWhenEntering' as AlertSettingsEnum,
        SendWhenExiting: 'SendWhenExiting' as AlertSettingsEnum,
        SendWhenEnteringOrExiting: 'SendWhenEnteringOrExiting' as AlertSettingsEnum
    };
}


