/**
 * ChronoSheets API
 * <div style=\'font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;\'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target=\'_BLANK\' href=\'http://tsheets.xyz/signup\'>http://tsheets.xyz/signup</a>.  </p></div><div id=\'cs-extra-info\'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationPricingPlan } from './organisationPricingPlan';


export interface Organisation { 
    Id?: number;
    Name?: string;
    AddressLine01?: string;
    AddressLine02?: string;
    Suburb?: string;
    State?: string;
    Postcode?: string;
    Country?: string;
    Phone?: string;
    EmailAddress?: string;
    Timezone?: string;
    SubscriptionCustomerId?: string;
    SignupToken?: string;
    IsActive?: boolean;
    StripeCouponCode?: string;
    SubscriptionSource?: Organisation.SubscriptionSourceEnum;
    SignUpSource?: Organisation.SignUpSourceEnum;
    MobileSignUpCode?: string;
    SubscriptionCycleStart?: string;
    SubscriptionCycleEnd?: string;
    PricingPlans?: Array<OrganisationPricingPlan>;
}
export namespace Organisation {
    export type SubscriptionSourceEnum = 'None' | 'Stripe' | 'AppleInApp' | 'GoogleInApp';
    export const SubscriptionSourceEnum = {
        None: 'None' as SubscriptionSourceEnum,
        Stripe: 'Stripe' as SubscriptionSourceEnum,
        AppleInApp: 'AppleInApp' as SubscriptionSourceEnum,
        GoogleInApp: 'GoogleInApp' as SubscriptionSourceEnum
    };
    export type SignUpSourceEnum = 'Desktop' | 'MobileiOS' | 'MobileAndroid';
    export const SignUpSourceEnum = {
        Desktop: 'Desktop' as SignUpSourceEnum,
        MobileiOS: 'MobileiOS' as SignUpSourceEnum,
        MobileAndroid: 'MobileAndroid' as SignUpSourceEnum
    };
}


