/**
 * ChronoSheets API
 * <div style=\'font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;\'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target=\'_BLANK\' href=\'http://tsheets.xyz/signup\'>http://tsheets.xyz/signup</a>.  </p></div><div id=\'cs-extra-info\'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationPricingPlan } from './organisationPricingPlan';


/**
 * An organisation in ChronoSheets
 */
export interface Organisation { 
    /**
     * The ID of the organisation
     */
    Id?: number;
    /**
     * The name of the organisation
     */
    Name?: string;
    /**
     * Address line 1 of the organisation
     */
    AddressLine01?: string;
    /**
     * Address line 2 of the organisation
     */
    AddressLine02?: string;
    /**
     * The suburb where the organisation is located
     */
    Suburb?: string;
    /**
     * The state where the organisation is located
     */
    State?: string;
    /**
     * The postcode of the organisation
     */
    Postcode?: string;
    /**
     * The country of the organisation
     */
    Country?: string;
    /**
     * The primary phone contact number of the organisation
     */
    Phone?: string;
    /**
     * The primary email address of the organisation
     */
    EmailAddress?: string;
    /**
     * The timezone of the organisation
     */
    Timezone?: string;
    /**
     * The customer ID of the payments subscription
     */
    SubscriptionCustomerId?: string;
    /**
     * The sign up token
     */
    SignupToken?: string;
    /**
     * Whether or not the organisation is active
     */
    IsActive?: boolean;
    /**
     * The payments coupon code
     */
    StripeCouponCode?: string;
    /**
     * The source of the subscription
     */
    SubscriptionSource?: Organisation.SubscriptionSourceEnum;
    /**
     * The source where the organisation signed up
     */
    SignUpSource?: Organisation.SignUpSourceEnum;
    /**
     * A temporary mobile sign up code
     */
    MobileSignUpCode?: string;
    /**
     * The start date and time of the organisations subscription
     */
    SubscriptionCycleStart?: string;
    /**
     * The end date and time of the organisations subscription
     */
    SubscriptionCycleEnd?: string;
    /**
     * The organisation\'s pricing plans
     */
    PricingPlans?: Array<OrganisationPricingPlan>;
}
export namespace Organisation {
    export type SubscriptionSourceEnum = 'None' | 'Stripe' | 'AppleInApp' | 'GoogleInApp';
    export const SubscriptionSourceEnum = {
        None: 'None' as SubscriptionSourceEnum,
        Stripe: 'Stripe' as SubscriptionSourceEnum,
        AppleInApp: 'AppleInApp' as SubscriptionSourceEnum,
        GoogleInApp: 'GoogleInApp' as SubscriptionSourceEnum
    };
    export type SignUpSourceEnum = 'Desktop' | 'MobileiOS' | 'MobileAndroid';
    export const SignUpSourceEnum = {
        Desktop: 'Desktop' as SignUpSourceEnum,
        MobileiOs: 'MobileiOS' as SignUpSourceEnum,
        MobileAndroid: 'MobileAndroid' as SignUpSourceEnum
    };
}


