/**
 * ChronoSheets API
 * <div style=\'font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;\'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target=\'_BLANK\' href=\'http://tsheets.xyz/signup\'>http://tsheets.xyz/signup</a>.  </p></div><div id=\'cs-extra-info\'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Fields used to save a Client
 */
export interface SaveClientRequest { 
    /**
     * The Id of the Client
     */
    Id?: number;
    /**
     * The name of the Client
     */
    ClientName?: string;
    /**
     * Address line 1 of the Client
     */
    ClientAddressLine1?: string;
    /**
     * Address line 2 of the Client
     */
    ClientAddressLine2?: string;
    /**
     * The suburb of the Client\'s address
     */
    ClientSuburb?: string;
    /**
     * The state of the Client\'s address
     */
    ClientState?: string;
    /**
     * The post code of the Client\'s address
     */
    ClientPostCode?: string;
    /**
     * The name of the contact working with the Client
     */
    PersonOfContact?: string;
    /**
     * The phone number of the Client
     */
    ClientPhoneNumber?: string;
    /**
     * The mobile phone number of the Client
     */
    ClientMobileNumber?: string;
    /**
     * The email address of the Client
     */
    ClientEmailAddress?: string;
    /**
     * The Client\'s website URL
     */
    ClientWebURL?: string;
}

