/**
 * ChronoSheets API
 * <div style=\'font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;\'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target=\'_BLANK\' href=\'http://tsheets.xyz/signup\'>http://tsheets.xyz/signup</a>.  </p></div><div id=\'cs-extra-info\'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Field for updating your Organisation
 */
export interface UpdateOrganisationRequest { 
    /**
     * The Id of your Organisation.  This is validated based on your current Auth Token
     */
    OrgansationId?: number;
    /**
     * The updated organisation name
     */
    OrganisationName?: string;
    /**
     * The updated Address Line 1 value
     */
    AddressLine01?: string;
    /**
     * The updated Address Line 2 value
     */
    AddressLine02?: string;
    /**
     * The updated address suburb
     */
    OrganisationSuburb?: string;
    /**
     * The updated address state
     */
    OrganisationState?: string;
    /**
     * The updated address postcode
     */
    OrganisationPostcode?: string;
    /**
     * The updated address country
     */
    OrganisationCountry?: string;
    /**
     * The updated contact phone number
     */
    OrganisationPhone?: string;
    /**
     * The update organisation email address
     */
    OrganisationEmailAddress?: string;
}

