export * from './aggregateJobTasks.service';
import { AggregateJobTasksService } from './aggregateJobTasks.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './fleet.service';
import { FleetService } from './fleet.service';
export * from './jobCodes.service';
import { JobCodesService } from './jobCodes.service';
export * from './organisation.service';
import { OrganisationService } from './organisation.service';
export * from './organisationGroupUsers.service';
import { OrganisationGroupUsersService } from './organisationGroupUsers.service';
export * from './organisationGroups.service';
import { OrganisationGroupsService } from './organisationGroups.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './timesheets.service';
import { TimesheetsService } from './timesheets.service';
export * from './trips.service';
import { TripsService } from './trips.service';
export * from './userJobFavourites.service';
import { UserJobFavouritesService } from './userJobFavourites.service';
export * from './userPayRates.service';
import { UserPayRatesService } from './userPayRates.service';
export * from './userProfile.service';
import { UserProfileService } from './userProfile.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './usualHours.service';
import { UsualHoursService } from './usualHours.service';
export const APIS = [AggregateJobTasksService, ClientsService, FleetService, JobCodesService, OrganisationService, OrganisationGroupUsersService, OrganisationGroupsService, ProjectsService, ReportsService, TasksService, TimesheetsService, TripsService, UserJobFavouritesService, UserPayRatesService, UserProfileService, UsersService, UsualHoursService];
