/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CSCSApiResponseCombinedReportsData } from '../ChronoSheetsClientLibModel/cSCSApiResponseCombinedReportsData';
import { CSCSApiResponseForPaginatedListOrgReportTimesheetFileAttachment } from '../ChronoSheetsClientLibModel/cSCSApiResponseForPaginatedListOrgReportTimesheetFileAttachment';
import { CSCSApiResponseForPaginatedListOrgReportTranscript } from '../ChronoSheetsClientLibModel/cSCSApiResponseForPaginatedListOrgReportTranscript';
import { CSCSApiResponseForPaginatedListOrgReportTrip } from '../ChronoSheetsClientLibModel/cSCSApiResponseForPaginatedListOrgReportTrip';
import { CSCSApiResponseForPaginatedListRawReportItem } from '../ChronoSheetsClientLibModel/cSCSApiResponseForPaginatedListRawReportItem';
import { CSCSApiResponseListFleetSummaryReportItem } from '../ChronoSheetsClientLibModel/cSCSApiResponseListFleetSummaryReportItem';
import { CSCSApiResponseListJobSeriesReportItem } from '../ChronoSheetsClientLibModel/cSCSApiResponseListJobSeriesReportItem';
import { CSCSApiResponseListProjectCostingReportItem } from '../ChronoSheetsClientLibModel/cSCSApiResponseListProjectCostingReportItem';
import { CSCSApiResponseTrip } from '../ChronoSheetsClientLibModel/cSCSApiResponseTrip';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ReportsService {

    protected basePath = 'https://api.chronosheets.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get Consolidated Admin Reports Data (Jobs, Tasks, Clients and Projects).  These are the organisation wide reports, with data from potentially all employees.    Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param forceOnlyThisChart A flag to indicate which report data you require.  Choose a particular set of data, or if you want all data use the &#39;NotForced&#39; option.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetAllChartsDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, forceOnlyThisChart?: 'NotForced' | 'SeriesJobCodes' | 'SeriesClients' | 'SeriesProjects' | 'SeriesTasks' | 'TotalsClients' | 'TotalsJobCodes' | 'TotalsProjects' | 'TotalsTasks', observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseCombinedReportsData>;
    public reportsGetAllChartsDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, forceOnlyThisChart?: 'NotForced' | 'SeriesJobCodes' | 'SeriesClients' | 'SeriesProjects' | 'SeriesTasks' | 'TotalsClients' | 'TotalsJobCodes' | 'TotalsProjects' | 'TotalsTasks', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseCombinedReportsData>>;
    public reportsGetAllChartsDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, forceOnlyThisChart?: 'NotForced' | 'SeriesJobCodes' | 'SeriesClients' | 'SeriesProjects' | 'SeriesTasks' | 'TotalsClients' | 'TotalsJobCodes' | 'TotalsProjects' | 'TotalsTasks', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseCombinedReportsData>>;
    public reportsGetAllChartsDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, forceOnlyThisChart?: 'NotForced' | 'SeriesJobCodes' | 'SeriesClients' | 'SeriesProjects' | 'SeriesTasks' | 'TotalsClients' | 'TotalsJobCodes' | 'TotalsProjects' | 'TotalsTasks', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetAllChartsDataAdmin.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetAllChartsDataAdmin.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetAllChartsDataAdmin.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }
        if (forceOnlyThisChart !== undefined && forceOnlyThisChart !== null) {
            queryParameters = queryParameters.set('ForceOnlyThisChart', <any>forceOnlyThisChart);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseCombinedReportsData>(`${this.basePath}/Reports/GetAllChartsDataAdmin`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Consolidated User Reports Data (Jobs, Tasks, Clients and Projects).  These are the user&#39;s own reports.    Requires the &#39;ViewOwnReports&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetAllChartsDataUser(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseCombinedReportsData>;
    public reportsGetAllChartsDataUser(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseCombinedReportsData>>;
    public reportsGetAllChartsDataUser(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseCombinedReportsData>>;
    public reportsGetAllChartsDataUser(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetAllChartsDataUser.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetAllChartsDataUser.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetAllChartsDataUser.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseCombinedReportsData>(`${this.basePath}/Reports/GetAllChartsDataUser`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets a summary report, which includes total distance travelled and total running costs, for vehicles within your organisation  Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetFleetSummaryAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseListFleetSummaryReportItem>;
    public reportsGetFleetSummaryAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseListFleetSummaryReportItem>>;
    public reportsGetFleetSummaryAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseListFleetSummaryReportItem>>;
    public reportsGetFleetSummaryAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetFleetSummaryAdmin.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetFleetSummaryAdmin.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetFleetSummaryAdmin.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseListFleetSummaryReportItem>(`${this.basePath}/Reports/GetFleetSummaryAdmin`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get trip by Id, for reporting purposes.    Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param tripId The ID of the Trip you want to get
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetOrgTripById(tripId: number, xChronosheetsAuth: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseTrip>;
    public reportsGetOrgTripById(tripId: number, xChronosheetsAuth: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseTrip>>;
    public reportsGetOrgTripById(tripId: number, xChronosheetsAuth: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseTrip>>;
    public reportsGetOrgTripById(tripId: number, xChronosheetsAuth: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (tripId === null || tripId === undefined) {
            throw new Error('Required parameter tripId was null or undefined when calling reportsGetOrgTripById.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetOrgTripById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (tripId !== undefined && tripId !== null) {
            queryParameters = queryParameters.set('TripId', <any>tripId);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseTrip>(`${this.basePath}/Reports/GetOrgTripById`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reports on Organisation timesheet file attachments (files uploaded and attached to timesheet records)  Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param skip Skip this many items
     * @param take Take this many items
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetOrganisationTimesheetFileAttachments(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseForPaginatedListOrgReportTimesheetFileAttachment>;
    public reportsGetOrganisationTimesheetFileAttachments(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseForPaginatedListOrgReportTimesheetFileAttachment>>;
    public reportsGetOrganisationTimesheetFileAttachments(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseForPaginatedListOrgReportTimesheetFileAttachment>>;
    public reportsGetOrganisationTimesheetFileAttachments(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetOrganisationTimesheetFileAttachments.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetOrganisationTimesheetFileAttachments.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetOrganisationTimesheetFileAttachments.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('Skip', <any>skip);
        }
        if (take !== undefined && take !== null) {
            queryParameters = queryParameters.set('Take', <any>take);
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseForPaginatedListOrgReportTimesheetFileAttachment>(`${this.basePath}/Reports/GetOrganisationTimesheetFileAttachments`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reports on Organisation transcripts (When an audio file is attached, it will be automatically transcribed, these are the transcriptions)    Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param skip Skip this many items
     * @param take Take this many items
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param keywords Search the transcripts by keyword(s)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetOrganisationTranscripts(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, keywords?: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseForPaginatedListOrgReportTranscript>;
    public reportsGetOrganisationTranscripts(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, keywords?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseForPaginatedListOrgReportTranscript>>;
    public reportsGetOrganisationTranscripts(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, keywords?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseForPaginatedListOrgReportTranscript>>;
    public reportsGetOrganisationTranscripts(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, keywords?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetOrganisationTranscripts.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetOrganisationTranscripts.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetOrganisationTranscripts.');
        }





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('Skip', <any>skip);
        }
        if (take !== undefined && take !== null) {
            queryParameters = queryParameters.set('Take', <any>take);
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }
        if (keywords !== undefined && keywords !== null) {
            queryParameters = queryParameters.set('Keywords', <any>keywords);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseForPaginatedListOrgReportTranscript>(`${this.basePath}/Reports/GetOrganisationTranscripts`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reports on Organisation trips (GPS tracking from whole organisation).    Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param skip Skip this many items
     * @param take Take this many items
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetOrganisationTrips(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseForPaginatedListOrgReportTrip>;
    public reportsGetOrganisationTrips(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseForPaginatedListOrgReportTrip>>;
    public reportsGetOrganisationTrips(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseForPaginatedListOrgReportTrip>>;
    public reportsGetOrganisationTrips(startDate: Date, endDate: Date, xChronosheetsAuth: string, skip?: number, take?: number, userIds?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetOrganisationTrips.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetOrganisationTrips.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetOrganisationTrips.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('Skip', <any>skip);
        }
        if (take !== undefined && take !== null) {
            queryParameters = queryParameters.set('Take', <any>take);
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseForPaginatedListOrgReportTrip>(`${this.basePath}/Reports/GetOrganisationTrips`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Timesheets Raw Data.  This data details each timesheet record.  These are the organisation wide timesheet records, with data from potentially all employees.    Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param sort Decide which column to sort on
     * @param order Decide which direction to sort the column
     * @param skip Skip this many rows
     * @param take Take this many rows
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsGetRawDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, sort?: 'EmailAddress' | 'JobCode' | 'TaskName' | 'ClientName' | 'ProjectName' | 'StartDate' | 'EndDate' | 'SpanSeconds' | 'Description' | 'PayAmount' | 'PayOvertimeAmount' | 'TripCost' | 'TripDistanceMeters' | 'Username', order?: 'Ascending' | 'Descending', skip?: number, take?: number, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseForPaginatedListRawReportItem>;
    public reportsGetRawDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, sort?: 'EmailAddress' | 'JobCode' | 'TaskName' | 'ClientName' | 'ProjectName' | 'StartDate' | 'EndDate' | 'SpanSeconds' | 'Description' | 'PayAmount' | 'PayOvertimeAmount' | 'TripCost' | 'TripDistanceMeters' | 'Username', order?: 'Ascending' | 'Descending', skip?: number, take?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseForPaginatedListRawReportItem>>;
    public reportsGetRawDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, sort?: 'EmailAddress' | 'JobCode' | 'TaskName' | 'ClientName' | 'ProjectName' | 'StartDate' | 'EndDate' | 'SpanSeconds' | 'Description' | 'PayAmount' | 'PayOvertimeAmount' | 'TripCost' | 'TripDistanceMeters' | 'Username', order?: 'Ascending' | 'Descending', skip?: number, take?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseForPaginatedListRawReportItem>>;
    public reportsGetRawDataAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, sort?: 'EmailAddress' | 'JobCode' | 'TaskName' | 'ClientName' | 'ProjectName' | 'StartDate' | 'EndDate' | 'SpanSeconds' | 'Description' | 'PayAmount' | 'PayOvertimeAmount' | 'TripCost' | 'TripDistanceMeters' | 'Username', order?: 'Ascending' | 'Descending', skip?: number, take?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsGetRawDataAdmin.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsGetRawDataAdmin.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsGetRawDataAdmin.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (order !== undefined && order !== null) {
            queryParameters = queryParameters.set('Order', <any>order);
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('Skip', <any>skip);
        }
        if (take !== undefined && take !== null) {
            queryParameters = queryParameters.set('Take', <any>take);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseForPaginatedListRawReportItem>(`${this.basePath}/Reports/GetRawDataAdmin`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets project cost estimations VS actual cost for date range and users.    Requires the &#39;ReportAdmin&#39; permission.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param userIds A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsProjectCostingsAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseListProjectCostingReportItem>;
    public reportsProjectCostingsAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseListProjectCostingReportItem>>;
    public reportsProjectCostingsAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseListProjectCostingReportItem>>;
    public reportsProjectCostingsAdmin(startDate: Date, endDate: Date, xChronosheetsAuth: string, userIds?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsProjectCostingsAdmin.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsProjectCostingsAdmin.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsProjectCostingsAdmin.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (userIds !== undefined && userIds !== null) {
            queryParameters = queryParameters.set('UserIds', <any>userIds);
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseListProjectCostingReportItem>(`${this.basePath}/Reports/ProjectCostingsAdmin`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Timeseries jobs data for the logged in user.    Requires the &#39;ViewOwnReports&#39; or &#39;SubmitTimesheets&#39;.
     * 
     * @param startDate The start date for the date range.  Report data in the response is after this date
     * @param endDate The end date for the date range.  Report data in the response is before this date
     * @param xChronosheetsAuth The ChronoSheets Auth Token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsUserJobsOverTime(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe?: 'body', reportProgress?: boolean): Observable<CSApiResponseListJobSeriesReportItem>;
    public reportsUserJobsOverTime(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CSApiResponseListJobSeriesReportItem>>;
    public reportsUserJobsOverTime(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CSApiResponseListJobSeriesReportItem>>;
    public reportsUserJobsOverTime(startDate: Date, endDate: Date, xChronosheetsAuth: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling reportsUserJobsOverTime.');
        }

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling reportsUserJobsOverTime.');
        }

        if (xChronosheetsAuth === null || xChronosheetsAuth === undefined) {
            throw new Error('Required parameter xChronosheetsAuth was null or undefined when calling reportsUserJobsOverTime.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }

        let headers = this.defaultHeaders;
        if (xChronosheetsAuth !== undefined && xChronosheetsAuth !== null) {
            headers = headers.set('x-chronosheets-auth', String(xChronosheetsAuth));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'multipart/form-data'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CSApiResponseListJobSeriesReportItem>(`${this.basePath}/Reports/UserJobsOverTime`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
